import type { MissionDefinition } from "./types";

export const campaign = [
  {
    id: "before-the-turn",
    sequence: 0,
    act: "I",
    title: "Before the Turn",
    location: "Turnward depot",
    objective: "Inspect three thresholds and move residents before a routine test shift.",
    teaches: ["movement", "interaction", "cover", "shift preview"],
  },
  {
    id: "receiving-light",
    sequence: 1,
    act: "I",
    title: "Receiving Light",
    location: "Contact dock",
    objective: "Escort the survey team, then extract when emergency custody begins.",
    teaches: ["strike", "guard", "incapacitation", "retrieval officer"],
  },
  {
    id: "emergency-custody",
    sequence: 2,
    act: "I",
    title: "Emergency Custody",
    location: "Receiving concourse",
    objective: "Open an escape route and recover the public transit keys.",
    teaches: ["enemy intent", "marked", "brace carrier"],
  },
  {
    id: "the-unreceived",
    sequence: 3,
    act: "II",
    title: "The Unreceived",
    location: "Residential shell",
    objective: "Reach households omitted from the official evacuation register.",
    teaches: ["restrained", "drone", "assist", "live shift"],
  },
  {
    id: "willing-passage",
    sequence: 4,
    act: "II",
    title: "Willing Passage",
    location: "Orchard reservoir",
    objective: "Escort voluntary evacuees to a civilian transport.",
    teaches: ["escort group", "departure auxiliary", "third party"],
  },
  {
    id: "the-quiet-map",
    sequence: 5,
    act: "II",
    title: "The Quiet Map",
    location: "Civic archive",
    objective: "Recover transition records and transmit the concealed forecast.",
    teaches: ["surveyor lane", "evidence", "alternate route"],
  },
  {
    id: "a-safe-shape",
    sequence: 6,
    act: "II",
    title: "A Safe Shape",
    location: "Stabilizer works",
    objective: "Disable three lock relays before the geometry freezes.",
    teaches: ["lock engineer", "linked device", "linebreaker rig"],
  },
  {
    id: "terms-of-survival",
    sequence: 7,
    act: "III",
    title: "Terms of Survival",
    location: "Assembly chamber",
    objective: "Keep the open assembly broadcasting through three testimony rounds.",
    teaches: ["field coordinator", "defensive movement", "surrender cascade"],
  },
  {
    id: "homeomorph",
    sequence: 8,
    act: "III",
    title: "Homeomorph",
    location: "Central anchor",
    objective: "Repair the anchors, disable the lock, and preserve voluntary passage.",
    teaches: ["mastery", "combined shifts"],
  },
  {
    id: "aftershape",
    sequence: 9,
    act: "Epilogue",
    title: "Aftershape",
    location: "Turnward depot",
    objective: "Walk the changed district and submit Crew Seven's public report.",
    teaches: ["consequence", "reflection"],
  },
] as const satisfies readonly MissionDefinition[];
