import type { SkillChoiceDefinition } from "./types";

export const skillChoices = [
  ["mara-holdfast", "mara", 1, "Anchor", "Holdfast", "Guard also makes Mara Braced."],
  ["mara-clear-order", "mara", 1, "Coordinator", "Clear Order", "Give an ally one movement AP."],
  ["mara-shelter-line", "mara", 2, "Anchor", "Shelter Line", "Adjacent allies share Mara's cover."],
  [
    "mara-hand-signal",
    "mara",
    2,
    "Coordinator",
    "Hand Signal",
    "Retarget one legal intent to Mara.",
  ],
  [
    "mara-here-we-stand",
    "mara",
    3,
    "Anchor",
    "Here We Stand",
    "Nearby allies gain Guard and clear Restrained.",
  ],
  ["mara-second-plan", "mara", 3, "Coordinator", "Second Plan", "Ready one ally once per mission."],
  [
    "iven-read-threshold",
    "iven",
    1,
    "Pathfinder",
    "Read Threshold",
    "Preview a shift early and gain one move.",
  ],
  [
    "iven-angle-found",
    "iven",
    1,
    "Opportunist",
    "Angle Found",
    "Strikes after moving gain one power.",
  ],
  [
    "iven-slip-route",
    "iven",
    2,
    "Pathfinder",
    "Slip Route",
    "Cross one ally and one closed threshold.",
  ],
  [
    "iven-pass-it-on",
    "iven",
    2,
    "Opportunist",
    "Pass It On",
    "A resolved mark transfers to the nearest enemy.",
  ],
  [
    "iven-known-way",
    "iven",
    3,
    "Pathfinder",
    "Known Way",
    "Connect two mapped gates for one round.",
  ],
  [
    "iven-already-gone",
    "iven",
    3,
    "Opportunist",
    "Already Gone",
    "Move a full range after striking.",
  ],
  ["sela-field-care", "sela", 1, "Triage", "Field Care", "Assist restores two vitality."],
  [
    "sela-terms-spoken",
    "sela",
    1,
    "Advocate",
    "Terms Spoken",
    "Surrender applies one vitality earlier.",
  ],
  [
    "sela-stabilize",
    "sela",
    2,
    "Triage",
    "Stabilize",
    "Restore one incapacitated ally once per mission.",
  ],
  ["sela-witness", "sela", 2, "Advocate", "Witness", "Adjacent enemies lose command bonuses."],
  ["sela-nobody-lost", "sela", 3, "Triage", "Nobody Lost", "Clear conditions in a two-tile area."],
  [
    "sela-open-corridor",
    "sela",
    3,
    "Advocate",
    "Open Corridor",
    "Create a zone enemies avoid this round.",
  ],
  ["tarn-good-brace", "tarn", 1, "Builder", "Good Brace", "Constructed cover has two integrity."],
  ["tarn-shear-pin", "tarn", 1, "Breaker", "Shear Pin", "Strikes against devices gain two power."],
  ["tarn-bypass", "tarn", 2, "Builder", "Bypass", "Interact with mechanisms from two tiles."],
  ["tarn-make-a-door", "tarn", 2, "Breaker", "Make a Door", "Destroy one weak wall per mission."],
  [
    "tarn-neighborhood-grid",
    "tarn",
    3,
    "Builder",
    "Neighborhood Grid",
    "Link two braces to project cover.",
  ],
  [
    "tarn-clean-stop",
    "tarn",
    3,
    "Breaker",
    "Clean Stop",
    "Disable a machine without its defeat effect.",
  ],
  [
    "nera-countermand",
    "nera",
    1,
    "Interdictor",
    "Countermand",
    "Jam an intent aimed at an objective.",
  ],
  [
    "nera-known-procedure",
    "nera",
    1,
    "Witness",
    "Known Procedure",
    "Reveal reinforcement timing and tiles.",
  ],
  [
    "nera-return-order",
    "nera",
    2,
    "Interdictor",
    "Return Order",
    "Reflect a coordinator's granted intent.",
  ],
  [
    "nera-chain-of-custody",
    "nera",
    2,
    "Witness",
    "Chain of Custody",
    "One evidence interaction costs zero AP.",
  ],
  [
    "nera-stand-down",
    "nera",
    3,
    "Interdictor",
    "Stand Down",
    "Eligible nearby human enemies surrender.",
  ],
  ["nera-full-record", "nera", 3, "Witness", "Full Record", "Copy one enemy command skill."],
].map(([id, characterId, tier, branch, name, effect]) => ({
  id,
  characterId,
  tier,
  branch,
  name,
  effect,
})) as readonly SkillChoiceDefinition[];
